Add Button component, styled and tested
isdi-coders-2023/coding-adventure-Victor-Granda-front-202301-BCN pull request #1
Opened 2023-02-27 15:14 UTC by Vegm92

2023-02-27 15:51 UTC, MMLORENA requested changes
Te faltan los resets y estilos generales

2023-02-27 15:51 UTC, MMLORENA commented on src/components/Button/Button.test.tsx
> +      render(<Button text={"a button"} />);
El texto del button es un magic string

2023-02-27 15:51 UTC, MMLORENA commented on src/components/Button/Button.tsx
> +export interface buttonProps {
¿Cómo escribimos las interfaces?

2023-02-27 15:51 UTC, MMLORENA commented on src/components/Form/Form.tsx
> +export let a: string;
Este archivo no debería estar.

2023-02-27 15:51 UTC, MMLORENA commented on src/components/Button/ButtonStyled.tsx
> +  }
Te faltan estilos del button.

2023-02-27 16:14 UTC, Vegm92 commented on src/components/Button/Button.test.tsx
> +      render(<Button text={"a button"} />);
done!

2023-02-27 16:14 UTC, Vegm92 commented on src/components/Button/Button.tsx
> +export interface buttonProps {
fixed!

2023-02-27 16:14 UTC, Vegm92 commented on src/components/Button/ButtonStyled.tsx
> +  }
media query done!

2023-02-27 16:49 UTC, MMLORENA submitted a review, later dismissed

2023-02-27 16:49 UTC, MMLORENA commented on src/components/Inputbar/InputBar.tsx
> +    <>
No me queda claro qué es este componente. Solo debes crear un componente Form

2023-02-28 10:55 UTC, Vegm92 commented on src/App.tsx
> +      <GlobalStyles />
fixed

2023-02-28 10:59 UTC, Vegm92 commented on src/components/Button/Button.test.tsx
> +      const mockText = "a button";
fixed!

2023-02-28 14:36 UTC, Vegm92 commented on src/components/Inputbar/InputBar.tsx
> +    <>
ok, lo adapto, me iba a hacr un componente para cada inputbar.

2023-02-28 14:36 UTC, Vegm92 commented on src/components/Inputbar/InputBar.tsx
> +  className,
Lo replanteo

2023-02-28 14:37 UTC, Vegm92 commented on src/components/Form/Form.tsx
> +export const Form = (): JSX.Element => {
ok

2023-02-28 14:37 UTC, Vegm92 commented on src/components/Button/ButtonStyled.tsx
>    color: black;
Listo!

2023-02-28 15:01 UTC, bertoforteza approved these changes

2023-02-28 15:09 UTC, merged

2023-02-28 15:10 UTC, Vegm92 commented
Merci!